name: music_player_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_media_metadata: ^1.0.0+1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  audioplayers: ^0.20.1
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  rxdart: ^0.27.7
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
